### ISSUE TITLE
[BUG] Indexing metadata never clears error_message -- a fixed bug appears live months later

### ISSUE THREAD

**Issue by jsbattig** [LightspeedDMS/code-indexer#1862]
# Indexing metadata never clears error_message, so a fixed bug looks live forever

`ProgressiveMetadata` writes `error_message` on failure and never removes it. Every later run
merges new fields over the old dict, so the string survives indefinitely and ends up sitting beside
`"status": "completed"`. An operator reading the file sees a current-looking error for a failure
that may be months old.

## Root cause

`src/code_indexer/services/progressive_metadata.py`:

- `fail_indexing()` (:141-145) sets `self.metadata["error_message"] = error_message`
- `complete_indexing()` (:133-139) sets `status`, `indexed_at`, `last_index_timestamp` -- and nothing
  else. `error_message` is untouched.
- `start_indexing()` (:98-117) calls `self.metadata.update({...})` -- a MERGE, and the key list does
  not include `error_message`, so a new run does not reset it either.

There is no path anywhere that removes the key. Once written, it is permanent.

## Observed on production (this is what makes it worth fixing)

`/opt/code-indexer/.cidx-server/data/golden-repos/.versioned/evolution/v_.../.code-indexer/metadata-voyage-ai.json`:

```json
"status": "completed",
"error_message": "'hnswlib.Index' object has no attribute 'check_integrity'"
```

A completed run carrying an AttributeError. That error is from **Bug #1415, filed 2026-07-15 and
already fixed** -- confirmed via the `self_monitoring_issues` table, and confirmed dead by direct
probe: both production interpreters (the server venv at `/opt/pipx/venvs/code-indexer` and the CLI's
`/usr/bin/python3`) have `check_integrity` and `repair_orphans` present, the
`hnswlib-last-built-commit` marker matches the `third_party/hnswlib` submodule at
`8155cfc9d02a5a46528a3faab697555952ed40c6`, and the last deploy reported success.

So the stale field caused a production bug report for an environment problem that does not exist,
and two agents plus this session spent real effort ruling it out.

## Impact

`error_message` currently carries no information about the run it appears in. It cannot be used to
triage, alert, or dashboard on, because a months-old string is indistinguishable from a live one.
The failure mode is silent and permanent: nothing ever clears it, and the surrounding `status` field
actively contradicts it.

## Expected

A successful run must not leave a failure message behind. `error_message` should describe the run
whose metadata it appears in, or be absent.

## Suggested direction (not a decision)

1. Clear the key in `complete_indexing()` -- `self.metadata.pop("error_message", None)`.
2. Clear it in `start_indexing()` too, so an in-progress run never displays the previous run's
   error. This also covers a crash between start and completion.
3. Consider whether `fail_indexing()` should stamp the failure time alongside the message, so even a
   correctly-current message is self-dating.

Options 1 and 2 together are the minimum; either alone leaves a window.

Whatever is chosen needs a discriminating test: fail a run, then complete one, and assert the key is
GONE -- not merely that `status` flipped. A test that only checks `status == "completed"` would pass
today.

## Note on existing production data

Metadata files already on disk keep their stale strings until their next indexing run rewrites them.
Worth deciding whether that matters enough to sweep, or whether natural churn is sufficient.

## Priority rationale

Rated priority-3. No incorrect indexing behaviour and no data at risk -- the cost is operator trust
and triage time, which this incident demonstrated concretely. The fix is a one-line change at two
call sites.

Found while investigating a production report of the #1415 AttributeError, 2026-09-15.

**Comment by jsbattig** [comment]
Code review of the fix (Claude, opus) returned REJECT on one blocking finding, now being remediated:

**Missed transition.** `start_indexing()` and `complete_indexing()` are not the only exits from a failed state. `SmartIndexer._do_resume_interrupted` (`smart_indexer.py:2099-2237`) is a third and calls neither — entry is gated by `can_resume_interrupted_operation()`, which explicitly accepts `status == "failed"` per Bug #467. On resume, `update_progress()` rewrites the whole document with a fresh `last_index_timestamp` and this run's `files_processed` while the previous run's `error_message` is still in the dict. Three terminal states persist that combination, including the cancelled-resume branch at :2226-2236. This is the production shape: golden-repo refresh shells out to `cidx index`, and the reported file was a golden-repo `metadata-voyage-ai.json`. Remedy: a narrow `ProgressiveMetadata.resume_indexing()` called at the top of the resume path (NOT `start_indexing()`, which would zero `files_processed`/`chunks_indexed` and corrupt resume accounting).

**Corollary worth recording.** The review enumerated every reader of `error_message` across `src/` and found **none** — `get_stats()` does not expose it, and the server's only reader of these files (`metadata_reader.py`) reads `status` and `current_commit` only. Every other hit belongs to an unrelated dict. The field is effectively write-only, which is precisely why the staleness went unnoticed for months. It also confirms `pop()` over `= None`: no consumer can distinguish absent from null, and `= None` would plant a permanent null in every metadata file on the fleet.

Sibling stale-field defects in the same module — one of which (`total_files_to_index` vs `files_processed` on the branch-change path) already produces a fabricated `remaining_files` — are filed separately as #1865 to keep this fix surgical.

**Comment by jsbattig** [comment]
## Dual review complete — both reviewers found a distinct missed exit

**Claude (opus): REJECT** — `_do_resume_interrupted` is a third exit from a failed state calling neither `start_indexing()` nor `complete_indexing()`. Closed with `ProgressiveMetadata.resume_indexing()` wired at the top of that method. Verified discriminating by mutation: neutralising `resume_indexing` to a no-op makes the new wiring test fail; restoring it passes.

**Codex (gpt-5.6-luna, verified real relay): REJECT** — a *fourth* path. Both incremental (`smart_indexer.py:1313`) and reconcile (`:1821`) guard `start_indexing()` behind `if status != "in_progress"`, so the pop is skipped there.

Codex approved the design itself on every other axis: `resume_indexing()` is proportionate rather than over-built (inline mutation would leak schema into the orchestrator; reusing `start_indexing()` would corrupt resume counters; reusing `complete_indexing()` is wrong because cancelled resumes must stay `failed`); its placement before the `get_remaining_files()` check is correct; resume semantics per Bug #467 are preserved; and the mocking boundary in the wiring test is honest, since the cancelled-resume branch means `complete_indexing()`'s own pop cannot be what satisfies the assertion.

### Reachability of the fourth path (checked, not assumed)

`status: "in_progress"` is written in exactly one place — `progressive_metadata.py:109`, inside `start_indexing()`. So post-fix the `in_progress` + `error_message` combination cannot be *created*; it can only be *read from disk*, written by the pre-fix code:

1. Old code: run 1 fails → `failed` + error.
2. Old code: run 2 calls `start_indexing()` → `in_progress`, error retained.
3. Run 2 is killed → disk holds `{"status": "in_progress", "error_message": ...}`.
4. New code: run 3 goes incremental/reconcile → hits the conditional → skips the pop → `update_progress()` rewrites the document with fresh counters beside run 1's error.

That is the original incident shape surviving the fix. It self-heals on the first run reaching `complete_indexing()`, so the window is narrower than the original bug, but it is reachable on any machine carrying such a file.

### Remediation — not Codex's proposed shape

Codex suggested a `clear_error_message()` method called from two further sites in `smart_indexer.py`. Rejected: that scatters metadata-schema knowledge into the orchestrator (the very thing Codex argued against elsewhere in its own review) and leaves four call sites to keep in sync.

Instead the pop goes in `ProgressiveMetadata.set_files_to_index()`, whose three production call sites are exactly the fresh-work boundaries and include both flagged paths:

```
smart_indexer.py:931    full indexing
smart_indexer.py:1343   incremental   <- flagged
smart_indexer.py:1827   reconcile     <- flagged
```

`_do_resume_interrupted` does not call it, so `resume_indexing()` keeps its own distinct responsibility. The `start_indexing()` pop stays as well — the branch-change path at `:595-601` calls `start_indexing()` then `complete_indexing()` with no `set_files_to_index()` between them.

The resulting rule is statable in one line: **recording a new work list, resuming, starting, or completing a run all mean the previous run's error no longer describes this run.**

Worth noting for the record: two independent reviewers each found a *different* missed exit from the same state. That this module has many exits, easy to enumerate incompletely, is itself the finding — and is why the sibling stale-field defects are filed as #1865 rather than patched key by key.

**Comment by jsbattig** [comment]
## Shipped to staging as v12.58.0 — but NOT validated end-to-end there, and here is why

`development` -> `staging` merged and deployed. CI green on both branches, tag `v12.58.0` cut, and the staging cluster node's server process is confirmed running 12.58.0 (restarted 04:30:45 by the auto-deploy).

**Local evidence is strong:**
- `fast-automation.sh` on a verified-idle box: 16082 passed, 0 failed, 0 pytest-timeouts, 25:36.
- 58 passed across the four targeted files.
- Both new guards independently mutation-verified: neutralising `resume_indexing` reds the resume test; neutralising only the `set_files_to_index` pop reds the legacy test. Neither is carried by the other.
- Dual review (Claude + Codex), each of which found a *different* missed exit.

**What I cannot claim:** that the fix has been exercised through the staging front door.

While verifying the deploy I found that the staging server resolves `cidx` to a shim pointing at a stale editable install — the server runs 12.58.0 while every `cidx index` subprocess it spawns runs **11.66.0**. Since this fix lives in `ProgressiveMetadata`, which is written by exactly that indexing subprocess, driving an index on staging right now would exercise 11.66.0 code and prove nothing about this change. Filed as **#1868** (priority-1).

Per the project's definition of done the honest phrasing is therefore: **gates green locally, NOT yet validated end to end in staging.** This issue should stay open until #1868 is resolved and an indexing run on staging can be confirmed to execute 12.58.0.

Worth noting separately that a *meaningful* staging check here is not trivial even once #1868 is fixed. The fix removes a stale field, so on a healthy repo "no `error_message` after a refresh" was already true beforehand and proves nothing. A discriminating check requires metadata that actually carries a stale error — i.e. deliberately seeding one into a staging repo's metadata file, then refreshing and confirming it is gone. That mutates staging state, so it should be an explicit decision rather than something done silently.

**Comment by jsbattig** [comment]
## Correction: the staging blocker I cited was not real

My previous comment held this open because "every `cidx index` subprocess staging spawns runs 11.66.0", citing #1868. **That was wrong** — #1868 is retracted and closed as invalid. I had probed `cidx` from my own SSH login, where a stale editable install in my home directory shadowed the real one. In the server's actual execution context (user `code-indexer`, systemd PATH/HOME), `cidx --version` reports **12.58.0**, the same version as the server, from the same source tree (`/opt/code-indexer-repo/src`).

So staging IS running this fix on the indexing path. The stated blocker is gone.

What remains true, and why this stays open a little longer: I still have not driven an actual index through the staging front door to observe the fix working. That is now a matter of *not having run it*, not of stale code — a much weaker reason than what I claimed.

The measurement problem I flagged earlier still stands, though. This fix REMOVES a stale field, so on a healthy repo "no `error_message` after a refresh" was already true beforehand and proves nothing. A discriminating staging check requires metadata that actually carries a stale error: seed one into a staging repo's metadata file, refresh through the front door, confirm it is gone. That mutates staging state, so it is a deliberate decision rather than something to do silently.

Local evidence is unchanged and strong: 58 targeted tests, `fast-automation.sh` green at 16082 passed with zero timeouts on a verified-idle box, dual review with each reviewer finding a distinct missed exit, and both new guards independently mutation-verified.

**Comment by jsbattig** [comment]
## Validated end-to-end through the front door — the discriminating check, not a vacuous one

I held this open because the fix REMOVES a field, so "no `error_message` after a refresh" is already true on a healthy repo and proves nothing. The only check that discriminates is metadata that actually carries a stale error.

Done on solo staging (v12.59.0), against a real golden repo:

1. Confirmed no golden-repo metadata on the box carried `error_message` (so any later presence is meaningful).
2. Seeded `itsdangerous`'s `metadata-voyage-ai.json` with the exact legacy production shape — `"status": "in_progress"` plus `"error_message": "'hnswlib.Index' object has no attribute 'check_integrity'"`. That is the state only PRE-FIX code could write, left behind by a run killed mid-flight.
3. Triggered a refresh through the REST front door: `POST /api/admin/golden-repos/itsdangerous/refresh` -> 202 with a job id.
4. Re-read the persisted file.

```
BEFORE seeding : status=completed   error_message absent
SEEDED         : status=in_progress error_message PRESENT
AFTER refresh  : status=completed   error_message GONE
```

This exercises the **fourth gap** specifically, the one dual review found and which is reachable only from legacy on-disk state: because `status` was already `in_progress`, incremental and reconcile both skip `start_indexing()` (`smart_indexer.py:1313`, `:1821`) and therefore skip its pop. Only the `set_files_to_index()` clearing point can clear it. Before the fix the stale string would have survived this refresh and landed beside fresh counters — exactly the shape that manufactured the original false production report.

Backup taken before seeding, removed after; the repo's metadata is back to a clean `completed` state with no error field.

Shipped in v12.58.0, still present and working in v12.59.0 on both staging environments. Closing.
