### ISSUE TITLE
[BUG] Temporal watch mode calls undefined TemporalIndexer.index_commits_list (AttributeError)

### ISSUE THREAD

**Issue by jsbattig** [LightspeedDMS/code-indexer#1296]
## Summary

Temporal **watch mode** calls `self.temporal_indexer.index_commits_list(...)` at `src/code_indexer/cli_temporal_watch_handler.py:242` and `:413`, but `TemporalIndexer` has **no `index_commits_list` method** (`grep -rn "def index_commits_list" src/` returns nothing). Any watch-mode temporal reindex path that reaches those call sites raises `AttributeError: 'TemporalIndexer' object has no attribute 'index_commits_list'`.

## Pre-existing (NOT introduced by the #1290 temporal rewrite)

Verified undefined at commit `e113b57d` (the parent of the Story #1290 per-commit rewrite) — so this latent bug predates the temporal per-commit re-architecture. The comment at `cli_temporal_watch_handler.py:410` literally reads *"Note: This assumes TemporalIndexer has an index_commits_list method"* — i.e. an assumed-but-never-implemented method.

## Steps to reproduce

Trigger the temporal watch handler's incremental-commit path (the branch that calls `index_commits_list`).

## Expected

Watch mode incrementally indexes the given commits (via the real temporal indexing entry point).

## Actual

`AttributeError` — the method does not exist.

## Fix direction

Either implement `TemporalIndexer.index_commits_list(commit_list)` (a thin wrapper over the real per-commit indexing path), or rewire `cli_temporal_watch_handler` to call the actual public entry point (`index_commits()` / the per-commit pipeline). Coordinate with the Story #1290 per-commit architecture so watch mode uses the new adapter-driven path (voyage-context-4 / dual-embedder). Add a watch-mode test that exercises the incremental path end-to-end.

## Environment
- Branch: development (post-#1290 temporal per-commit rewrite)
- Files: `src/code_indexer/cli_temporal_watch_handler.py:242,410,413`; `src/code_indexer/services/temporal/temporal_indexer.py`
- Discovered during the Story #1290 code review (Epic #1289).
