### ISSUE TITLE
[BUG] MCP search_code single -global crashes: 'list' object has no attribute 'to_dict' (regression from #1202 in v10.164.0)

### ISSUE THREAD

**Issue by jsbattig** [LightspeedDMS/code-indexer#1219]
## Summary

MCP `search_code` for a **single global/activated repo** crashes with `'list' object has no attribute 'to_dict'`. This is a **regression introduced by the #1202 fix** (commit `c4c59d11`), discovered during front-door E2E validation of the v10.164.0 staging release. The primary `search_code` MCP tool is completely broken for single-repo `-global` queries.

## Severity

P1 — breaks the core `search_code` MCP tool for single global/activated repos cluster-wide. REST `/api/query` and MCP omni (multi-repo) paths are unaffected.

## Environment

- Staging cluster (PostgreSQL, 3 nodes behind HAProxy), v10.164.0, confirmed on all nodes (staging / node-22 / node-23).
- Front door: https://linner.ddns.net (MCP JSON-RPC).

## Reproduction (front door, MCP)

```
POST /mcp  (Authorization: Bearer <admin>)
{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"search_code",
 "arguments":{"query_text":"middleware","repository_alias":"fastapi-global","limit":3}}}
```

Response:
```json
{"success": false, "error": "'list' object has no attribute 'to_dict'", "results": []}
```

Reproduced on every node and for multiple repos (`fastapi-global`, `flask-global`) and every `search_mode` (semantic/fts/hybrid — semantic is the default and also fails, so this is NOT mode-specific).

### Blast radius (verified via front door)

| Path | Result |
|------|--------|
| MCP `search_code` single `-global` | **FAILS** (`'list' object has no attribute 'to_dict'`) |
| MCP `search_code` omni (array of aliases) | OK (own omni path) |
| MCP `regex_search` single `-global` | OK |
| REST `POST /api/query` semantic single repo | OK (HTTP 200) |

## Root cause

The #1202 commit `c4c59d11` changed `SemanticQueryManager._perform_search()` to return a 2-tuple `(results, effective_strategy)` instead of a plain `List[QueryResult]` (see `semantic_query_manager.py:981` -> `return (all_results[:effective_limit], _effective_strategy)`).

It updated the call site inside `query_user_repositories` (`semantic_query_manager.py:546-590`) to unpack the tuple:
```python
_raw = self._perform_search(...)
if isinstance(_raw, tuple):
    results, effective_strategy = _raw
else:
    results = _raw
```

But it **missed the second call site** in the MCP handler used by the single-repo `-global` path:

`src/code_indexer/server/mcp/handlers/search.py:954` (inside `_execute_tracked_search`):
```python
results = _utils.app_module.semantic_query_manager._perform_search(**kwargs)   # NOT unpacked
...
return results, execution_time_ms, timeout_occurred
```

`_search_global_repo` (handlers/search.py:970, dispatched for `-global` aliases at line 1252) calls `_execute_tracked_search`, gets back the **tuple** as `results`, then at `handlers/search.py:999` does:
```python
response_results = [r.to_dict() for r in results]
```
Iterating the 2-tuple yields `r = List[QueryResult]` (the first tuple element) -> `list.to_dict()` -> AttributeError.

There are exactly two `_perform_search()` call sites in `src/code_indexer/server/`:
- `semantic_query_manager.py:546` (fixed by #1202)
- `mcp/handlers/search.py:954` (MISSED by #1202)

## Fix

Unpack the tuple at `mcp/handlers/search.py:954` the same way `query_user_repositories` does, e.g.:
```python
_raw = _utils.app_module.semantic_query_manager._perform_search(**kwargs)
if isinstance(_raw, tuple):
    results, _effective_strategy = _raw
else:
    results = _raw
```
(Optionally thread `_effective_strategy` into the global-repo `query_metadata` to match AC7 coverage on this path.)

## Regression guard

Add a front-door / handler-level test that drives `search_code` for a single `-global` repo (default semantic mode) and asserts `success == true` with non-empty results. The existing #1202 guards covered the `query_user_repositories` path and the omni path but not the `_execute_tracked_search` / `_search_global_repo` single-repo `-global` path.

## Impact on v10.164.0 release

This is a release blocker for v10.164.0: the #1202 fix it ships regresses single-repo MCP `search_code`. Recommend a follow-up hotfix on development -> staging before any promotion.

**Comment by jsbattig** [comment]
Fixed via /implement-backlog (commit ff62fcd0, released in v10.165.0). Root cause: #1202 changed _perform_search to return (results, effective_strategy) and updated query_user_repositories but missed the 2nd caller _execute_tracked_search (mcp/handlers/search.py:954), so the single -global path iterated the tuple -> 'list' object has no attribute 'to_dict' on every mode. Fix: unpack the tuple at _execute_tracked_search (same guard as query_user_repositories) + thread effective_search_mode/effective_query_strategy into the global path's query_metadata (AC7 parity). Verified exactly 2 _perform_search call sites (both unpack) and 1 _execute_tracked_search caller (updated to 4-tuple). New test covers the single -global path (the gap that let #1202 ship the regression). Code review APPROVED. server-fast all 6 chunks green. Staging E2E (v10.165.0, all 3 cluster nodes): search_code -global now succeeds in semantic/fts/hybrid with the crash gone; the 4 other server fixes still pass; log audit clean.
