### ISSUE TITLE
[BUG] Remaining bare getattr() singleton probes in xray.py (5+ sites) and parallel files still cause order-dependent test failures + real singleton construction side effects

### ISSUE THREAD

**Issue by jsbattig** [LightspeedDMS/code-indexer#1709]
## Discovery

Found during code review of #1693 (xray.py's `_get_xray_executor`/`_get_xray_cell_limiter` readers fixed to route through `_lazy_singleton_app_or_none()` instead of side-effectful `getattr()`).

## Description

Several MORE bare `getattr(_utils.app_module, "app", None)`-style singleton probes remain in the same file (and parallel files), unfixed by #1693's scope:

- `src/code_indexer/server/mcp/handlers/xray.py:774-775`, `:1407-1408`, `:1540-1541`, `:1692`, `:1755`
- Parallel probes in `scip.py`, `repos.py`, `files.py` (not yet audited for the exact count)

These trigger the same PEP-562 `__getattr__` side effect #1693 just fixed for the two named readers -- constructing the process-wide app singleton as a side effect of merely reading it.

## Impact (confirmed, not speculative)

The #1693 reviewer PROVED this has a real, currently-observable effect, not just theoretical risk: `test_query_admission_gate_wiring_1600.py`'s `test_xray_handle_xray_search`/`test_xray_handle_xray_explore` fail when run STANDALONE (not in the full suite) because `xray.py:774`'s bare `getattr` construction runs before the tests' patched wrappers take effect, dying inside the file's autouse `_StubConfigService` fixture with `AttributeError: '_StubConfigService' object has no attribute 'initialize_runtime_db'` -- an exception silently swallowed by `_run_denied_then_allowed`, causing the tests' own assertions to fail non-obviously.

The reviewer verified the fix's payoff directly: routing `xray.py:774`'s probe through the same `_lazy_singleton_app_or_none()` helper #1693 introduced makes both tests pass standalone, genuinely removing the order-dependence (`CURRENT (bare getattr): allowed_called=False -> FAIL` vs `PROPOSED (safe probe): allowed_called=True -> PASS`).

Confirmed pre-existing and NOT introduced by #1693 -- the order-dependence exists identically on the parent commit.

## Expected

Route all remaining bare `getattr(app_module, "app", ...)`-style probes in `xray.py` (lines 774-775, 1407-1408, 1540-1541, 1692, 1755) through `_lazy_singleton_app_or_none()`, following #1693's established pattern exactly. Audit `scip.py`/`repos.py`/`files.py` for the same pattern and fix those too if present.

Also: `tests/unit/server/mcp/test_query_admission_gate_wiring_1600.py:411-412`'s comment claims the #1693 test-fixture fix "verifies the exact same ordering without ever touching the real singleton" -- this is factually incorrect (the singleton IS still constructed via the unfixed `xray.py:774` probe during the test). Correct the comment to say "without the patch-time construction side effect" once this issue's fix lands (or independently, since the comment inaccuracy exists regardless of when the remaining probes get fixed).

## Scope note

Filed as a dedicated follow-up per the #1693 review's finding; not fixed as part of #1693 (that fix's scope was specifically the two named readers plus xray_batch.py's copy; these are additional, related-but-separate call sites in the same broader anti-pattern class).

**Comment by jsbattig** [comment]
Fixed via commits 45e7fa4e + fe088765 (remaining bare app-module getattr probes routed through the safe lazy helper, code-review remediation applied). Deployed to staging as part of v12.27.0.
